// <auto-generated />
using ListaDesejosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ListaDesejosAPI.Migrations
{
    [DbContext(typeof(UsuarioContext))]
    [Migration("20220322211220_Relacionando desejo e usuario")]
    partial class Relacionandodesejoeusuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("ListaDesejosAPI.Data.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Loguin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ListaDesejosAPI.Models.Desejo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioID")
                        .IsUnique();

                    b.ToTable("Desejos");
                });

            modelBuilder.Entity("ListaDesejosAPI.Models.Desejo", b =>
                {
                    b.HasOne("ListaDesejosAPI.Data.Usuario", "Usuario")
                        .WithOne("Desejo")
                        .HasForeignKey("ListaDesejosAPI.Models.Desejo", "UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ListaDesejosAPI.Data.Usuario", b =>
                {
                    b.Navigation("Desejo");
                });
#pragma warning restore 612, 618
        }
    }
}
